### ISSUE TITLE
Endlessly comments downloading.

### ISSUE THREAD

**Issue by lerdem** [egbertbouman/youtube-comment-downloader#70] opened 2021-02-19 21:35 UTC
An example video id is `NrprYX6LRVY`. That video has around 100 comments, but script continuously downloading duplicated comments. 
This is a bug in script?

Used version hash `a69cb5f3ce7d3183e589e15df63e6ab10e0251f5`

**Comment by egbertbouman** [comment] 2021-02-19 21:53
Duplicate of https://github.com/egbertbouman/youtube-comment-downloader/issues/68. This should already be fixed.

**Closed by egbertbouman** 2021-02-19 21:53 UTC
