### ISSUE TITLE
Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by gitdude1** [egbertbouman/youtube-comment-downloader#60] opened 2020-12-06 23:31 UTC
This error started occurring a few days ago. It occurs for all youtube videos. No changes were made to my system.
I'm using the most recent version of youtube-comment-downloader (aug-2020) with Linux Mint 18.3, 
Python 2.7.11
python-requests 2.9.1
python-lxml 3.5.0
python-cssselect 0.9.1
I tried it from Linux Mint 19.3 live USB (released dec-2019) and get the same error.

I added the following code:
	    # Debug
	    print(response.text)
            return response.json()
and get:
Downloading Youtube comments for video: WRm2oUw4owE
Downloaded 0 comment(s)
Error: No JSON object could be decoded

**Comment by d0tN3t** [comment] 2020-12-07 11:44
@gitdude1 Something changed and I'm posting on this open issue to let you know that the prior open issue before yours is a duplicate issue. So I'll mainly be responding to that one to keep the chatter down.

**Comment by egbertbouman** [comment] 2020-12-07 12:13
Duplicate of https://github.com/egbertbouman/youtube-comment-downloader/issues/59.

**Closed by egbertbouman** 2020-12-07 12:13 UTC
