### ISSUE TITLE
Bug: Unable to download comments from a YouTube live archive

### ISSUE THREAD

**Issue by minamotorin** [egbertbouman/youtube-comment-downloader#61] opened 2020-12-16 18:19 UTC
This issue started after the latest update (#59).

When I try to download comments from a YouTube live archive, none of them are downloaded even though the comments exist. No error occured. The log just says there were 0 comments.

I confirmed the following:
  - This issue does not occur at a Premieres
  - It does not matter the archive length or if the archive has chats or recording or not
  - No problem with other YouTube videos

Environment: 
  - macOS 10.15.6
  - Python 3.9.0 with pyenv 1.2.21
  - lxml 4.6.2
  - requests 2.25.0
  - cssselect 1.1.0

Log:

  ```
  $ python ./downloader.py -y=GDASRRpWTf4 -o test.json
  Downloading Youtube comments for video: GDASRRpWTf4
  Downloaded 0 comment(s)
  [2.32 seconds] Done!
  ```

Test video:
  - https://www.youtube.com/watch?v=GDASRRpWTf4

**Comment by egbertbouman** [comment] 2020-12-16 19:38
Thanks for letting me know! I can confirm that the issue is with live streams only. After some investigation, it turned out that the code that checks whether a video is a live stream or not wasn't working anymore. I just pushed a fix for this.

**Closed by egbertbouman** 2020-12-16 19:38 UTC

**Comment by minamotorin** [comment] 2020-12-17 03:38
Thanks.
