### ISSUE TITLE
Error: local variable 'ncd' referenced before assignment

### ISSUE THREAD

**Issue by Dialga** [egbertbouman/youtube-comment-downloader#71] opened 2021-02-22 22:55 UTC
`Error: local variable 'ncd' referenced before assignment` when attempting to use this script.

**Comment by egbertbouman** [comment] 2021-02-23 11:57
I'm unable to reproduce this. Are you sure you are using the latest version, and if so, could you please give an example video ID?

**Comment by Dialga** [comment] 2021-02-23 14:08
I cloned it fresh right before trying the downloader.py script.
I figured out what the issue is, I had passed the full url to -y rather than just the videoid, thinking this would be similar to youtube-dl.
That triggers this error.

**Comment by egbertbouman** [comment] 2021-02-23 16:51
OK, thanks for letting me know. I'll close this issue then.

**Closed by egbertbouman** 2021-02-23 16:51 UTC
