### ISSUE TITLE
Error: Document is empty

### ISSUE THREAD

**Issue by khiemnd5** [egbertbouman/youtube-comment-downloader#45] opened 2020-07-29 18:11 UTC
I had problem when run code:
Link example youtube: https://www.youtube.com/watch?v=sMAVhkFEeRw
![image](https://user-images.githubusercontent.com/11885651/88836838-8d8f4b00-d201-11ea-88ed-a11b430c59b8.png)

Do you have any idea?
Thank you so much!

**Comment by spiralofhope** [comment] 2020-07-29 22:35
It works for me using the latest version from git (`ec268fd077c438093c4be1d8b000b90dde03f2ab`).  I don't think you are using the same version, because I don't see the timer.  Update your copy from git and see if that helps.

``` bash
./downloader.py --youtubeid sMAVhkFEeRw --output demo.json
```

```
Downloading Youtube comments for video: sMAVhkFEeRw
Downloaded 15 comment(s)
[1.39 seconds] Done!
```

**Comment by khiemnd5** [comment] 2020-07-30 01:50
@spiralofhope  thank you reply me.
I was checked.
In python version 3.7 not working. Version 2.7 worked.

> python3 downloader.py --youtubeid sMAVhkFEeRw --output demo.json
Downloading Youtube comments for video: sMAVhkFEeRw
Error: Document is empty
====
python downloader.py --youtubeid sMAVhkFEeRw --output demo.json
Downloading Youtube comments for video: sMAVhkFEeRw
Downloaded 15 comment(s)
[1.69 seconds] Done!

![image](https://user-images.githubusercontent.com/11885651/88870787-6f950b00-d240-11ea-9939-61b767791d15.png)

I don't know why this problem.
I was debugged the problem exception in this function.

` def extract_reply_cids(html):
    tree = lxml.html.fromstring(html)
    sel = CSSSelector('.comment-replies-header > .load-comments')
    return [i.get('data-cid') for i in sel(tree)] `

I provided more info.

**Comment by d0tN3t** [comment] 2020-07-31 06:55
@khiemnd5 I'm running 3.7 and I was able to download it as well.

![Screen Shot 2020-07-31 at 1 45 25 AM](https://user-images.githubusercontent.com/11362484/89008179-d44b7680-d2cf-11ea-9aa8-45cba21345d7.png)

Maybe it has to do with your `lxml` package if you debugged it to that code block you showed. My lxml version is 4.2.5. But I can't see that being the reason as I've used different ones in the past. If you can get it to work with 2.7 then my guess is that your python 3 environments may be conflicting for some reason. Possibly other packages. You could try setting up a new environment with all the packages needed to run the script. 

![Screen Shot 2020-07-31 at 1 55 07 AM](https://user-images.githubusercontent.com/11362484/89008782-e24dc700-d2d0-11ea-9a85-c6c1f265e088.png)

**Comment by d0tN3t** [comment] 2020-08-01 20:26
@egbertbouman I'm not sure if this is ready to be closed. I haven't received any feedback nor am I able to reproduce the error the user is receiving. 👍

**Comment by egbertbouman** [comment] 2020-08-01 21:16
@d0tN3t I've just tried it using Python 2.7/3.7/3.8, but couldn't reproduce it either. So, I'll close this issue for now. If we get more similar reports, I'll take another, closer look.

**Closed by egbertbouman** 2020-08-01 21:16 UTC
